vim.o.number = true
vim.o.relativenumber = true
vim.o.autoindent= true
vim.o.expandtab = true
vim.o.shiftwidth = 4
vim.o.tabstop = 4
vim.o.hlsearch = false
vim.o.swapfile = false
vim.o.termguicolors = true
vim.o.ignorecase = true
vim.o.background = 'dark'
vim.o.conceallevel = 1
vim.o.scrolloff = 999
